backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/pages/easyRead"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "easyReadPage"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Blurb", name: "blurb", widget: "string"}
      - {label: "Main image", name: 'image', widget: image}
      - {label: "Sections", name: "sections", widget: "list", fields:
        [
          {label: "Heading", name: heading, widget: "string"},
          {label: "Section Image", name: 'image', widget: image},
          {label: "Rows", name: rows, widget: list, fields:
            [
              {label: Text, name: body, widget: markdown},
              {label: Image, name: image, widget: image},
            ]
          }
        ]}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list"}
